### ISSUE TITLE
Request for comment

### ISSUE THREAD

**Issue by nsuchy** [TotallyTobyFox/undertale#12]
Hi @silica (@TotallyTobyFox). I've written a blog post about your project. (See: https://www.lunorian.is/undertale-source-code-leak/). Would you like to leave a comment? If so can you please send an email to me@lunorian.is? Thanks!

**Comment by ThatNerdyPikachu** [comment]
the github user is wrong.

look around bitbucket for GM:S related projects to find them 👀
