### ISSUE TITLE
What the heck is that soundtrack?

### ISSUE THREAD

**Issue by SCOTT0852** [TotallyTobyFox/undertale#6]
I tried compiling this to HTML, and it didn't run. I decided to listen to the soundtrack, but to my surprise Megalovania was a single 1 second long sound effect. I tried listening to Undyne's theme, and then Undyne the Undying's. They all seem to be one of a few random sound effects instead of their actual songs.

I looked through a bunch more other random files that started with mus_, every single one of them is a random sound effect. It didn't matter whether I tried the MP3s (which are not present in the Steam release) or the OGGs (which are present in the original release), both file types were affected.

**Comment by TotallyTobyFox** [comment]
I don't know someone just sent me these files

**Comment by TotallyTobyFox** [comment]
There you go, audio fixed.
